library(tidyverse)
require(stats4)
require(askpass)
library(datasets)
data("AirPassengers")
summary(AirPassengers)
plot(AirPassengers)
library(jsonlite)
library(datasets)
data(iris)
myjson<- toJSON(iris, pretty = TRUE)
myjson
